version: "3.9"
services:

  zoo-1:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zoo-1
    hostname: zoo-1
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    # volumes:
    #   - ./volume/zookeeper/data:/data
    #   - ./volume/zookeeper/datalog:/datalog
    networks:
      - kafka-net

  kafka-1:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka-1
    hostname: kafka-1
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zoo-1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    # volumes:
    #   - ./volume/kafka/data:/var/lib/kafka/data
    depends_on:
      - zoo-1
    networks:
      - kafka-net

  elastic-search:
    image: elasticsearch:8.5.1
    container_name: elastic1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    networks:
      - kafka-net
    ports:
      - 9200:9200
      - 9300:9300
    
  kibana:
    image: kibana:8.5.1
    container_name: kibana1
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTS}  
    networks:
      - kafka-net
    ports:
      - 5601:5601
    depends_on:
      - elastic-search

networks:
  kafka-net: